### ISSUE TITLE
Template option renders as string

### ISSUE THREAD

**Issue by mishingo** [iyonaga/ejs-templates-loader#5]
When I try to render a variable from plugin options it returns a string as such:

<％= htmlWebpackPlugin.options.title ％>

an example of my html instance:
```
new HtmlWebpackPlugin({
        filename: 'dist/navbar.html',
        template: 'src//navbar.ejs',
        minify: false,
        inject: false,
        title: 'title',
      })
```

**Comment by iyonaga** [comment]
@mishingo 
Could you try the following?

`<％= htmlWebpackPlugin.options.title ％>`
↓
`<%= htmlWebpackPlugin.options.title %>`

**Comment by mishingo** [comment]
This worked thank you!
